/**
 * RichInfographicViewer — renders a complete HTML infographic in a sandboxed
 * iframe. Provides zoom controls, fullscreen toggle, and export (PNG/PDF).
 *
 * The HTML is generated by the backend LLM and is fully self-contained
 * (inline CSS + SVG charts + Google Fonts import).
 */

import { useState, useRef, useCallback, useEffect } from 'react';
import {
  ZoomIn, ZoomOut, Maximize2, Minimize2, Download, Printer,
  FileImage, ChevronLeft,
} from 'lucide-react';

interface RichInfographicViewerProps {
  html: string;
  title?: string;
  onBack?: () => void;
}

const ZOOM_LEVELS = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.25, 1.5];

export function RichInfographicViewer({ html, title, onBack }: RichInfographicViewerProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [zoomIdx, setZoomIdx] = useState(3); // start at 0.8
  const [isFullscreen, setIsFullscreen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const zoom = ZOOM_LEVELS[zoomIdx];

  const zoomIn = () => setZoomIdx(i => Math.min(i + 1, ZOOM_LEVELS.length - 1));
  const zoomOut = () => setZoomIdx(i => Math.max(i - 1, 0));
  const zoomFit = () => setZoomIdx(3);

  const toggleFullscreen = useCallback(() => {
    if (!containerRef.current) return;
    if (!isFullscreen) {
      containerRef.current.requestFullscreen?.();
    } else {
      document.exitFullscreen?.();
    }
  }, [isFullscreen]);

  useEffect(() => {
    const handler = () => setIsFullscreen(!!document.fullscreenElement);
    document.addEventListener('fullscreenchange', handler);
    return () => document.removeEventListener('fullscreenchange', handler);
  }, []);

  // Write HTML into the iframe once loaded, then auto-resize to fit content
  const handleIframeLoad = useCallback(() => {
    const iframe = iframeRef.current;
    if (!iframe) return;
    const doc = iframe.contentDocument || iframe.contentWindow?.document;
    if (!doc) return;
    doc.open();
    doc.write(html);
    doc.close();

    // Auto-resize iframe to match content height
    const resizeIframe = () => {
      try {
        const body = iframe.contentDocument?.body;
        const html = iframe.contentDocument?.documentElement;
        if (body && html) {
          const h = Math.max(body.scrollHeight, body.offsetHeight, html.scrollHeight, html.offsetHeight);
          iframe.style.height = `${h + 40}px`;
        }
      } catch { /* cross-origin guard */ }
    };
    // Resize after fonts/images load
    setTimeout(resizeIframe, 300);
    setTimeout(resizeIframe, 1000);
    setTimeout(resizeIframe, 2500);
  }, [html]);

  // Re-write when html changes
  useEffect(() => {
    handleIframeLoad();
  }, [handleIframeLoad]);

  const handlePrint = () => {
    const iframe = iframeRef.current;
    if (!iframe?.contentWindow) return;
    iframe.contentWindow.focus();
    iframe.contentWindow.print();
  };

  const handleExportPNG = async () => {
    try {
      const { default: html2canvas } = await import('html2canvas');
      const iframe = iframeRef.current;
      if (!iframe?.contentDocument?.body) return;
      const canvas = await html2canvas(iframe.contentDocument.body, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff',
        width: 900,
        windowWidth: 900,
      });
      const link = document.createElement('a');
      link.download = `${title || 'infographic'}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (e) {
      console.error('PNG export failed:', e);
    }
  };

  return (
    <div ref={containerRef} className={`rich-ig-viewer ${isFullscreen ? 'rich-ig-viewer--fullscreen' : ''}`}>
      {/* Toolbar */}
      <div className="rich-ig-toolbar">
        <div className="rich-ig-toolbar-left">
          {onBack && (
            <button className="rich-ig-btn" onClick={onBack} title="Back to editor">
              <ChevronLeft size={14} />
            </button>
          )}
          <span className="rich-ig-toolbar-title">{title || 'Infographic'}</span>
        </div>

        <div className="rich-ig-toolbar-center">
          <button className="rich-ig-btn" onClick={zoomOut} disabled={zoomIdx <= 0}><ZoomOut size={14} /></button>
          <button className="rich-ig-zoom-label" onClick={zoomFit}>{Math.round(zoom * 100)}%</button>
          <button className="rich-ig-btn" onClick={zoomIn} disabled={zoomIdx >= ZOOM_LEVELS.length - 1}><ZoomIn size={14} /></button>
        </div>

        <div className="rich-ig-toolbar-right">
          <button className="rich-ig-btn" onClick={handleExportPNG} title="Export as PNG">
            <FileImage size={14} /> <span>PNG</span>
          </button>
          <button className="rich-ig-btn" onClick={handlePrint} title="Print / Save as PDF">
            <Printer size={14} /> <span>Print</span>
          </button>
          <button className="rich-ig-btn" onClick={toggleFullscreen} title={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}>
            {isFullscreen ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
          </button>
        </div>
      </div>

      {/* Canvas area */}
      <div className="rich-ig-canvas">
        <div
          className="rich-ig-frame-wrap"
          style={{ transform: `scale(${zoom})`, transformOrigin: 'top center' }}
        >
          <iframe
            ref={iframeRef}
            className="rich-ig-iframe"
            title="Infographic"
            sandbox="allow-same-origin allow-popups allow-modals allow-scripts"
            onLoad={handleIframeLoad}
          />
        </div>
      </div>
    </div>
  );
}
